### ISSUE TITLE
Phase3 Scoring mechanism and win condition is incorrect

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#15]
Unsure how the game is won.  According to spec, the game should win by whichever player has the least amount of "I Cannot Plays".  

Open as discussion in case this interpretation is wrong before proceeding to make changes.

REFERENCE BELOW FROM THE SPEC
**Who ever has the least number of "cannot plays", is the winner.  Declare this at the end, when the deck is exhausted.**

**Comment by hmason55** [comment]
The person who skips the least will still win. I made the point system add points for playing cards because I thought would be easier to understand for players, rather than decreasing points upon skipping and possibly going negative, they just don't get any for skipping. Playing a card successfully awards a point.

**Comment by mdoussias** [comment]
Seems reasonable.....  Tomorrow I'll add a short **"program description"** as notes at the top of the program that explains this.  Program looks awesome btw.

**Comment by mdoussias** [comment]
This was completed.  Program description added to top of program.
