### ISSUE TITLE
High card game still assigns points there is a tie

### ISSUE THREAD

**Issue by mdoussias** [team-makeSmart/M6-Time-High-Card#6]
- [ ] Any time there is a **tie**, the player that put their card down second wins a point.  When the human player puts a card down and the AI puts an equivalent card, the AI receives a point.     Similarly in reverse, when the AI puts a card down and the human puts a card of equal value, the human player gets a point.

**Comment by p12345vls** [comment]
It is because the card suit has higher value, I believe

**Comment by hmason55** [comment]
Like Pavlos mentioned, we take the suit and value into account when determining the winner so that's why two cards with the same value but different suits don't result in a tie. If we did want to make this a feature we could just remove the suit comparison condition and add a tie feature that gives neither players a point.
